export default {
  country: 'latvia',
  fromCountry: 'India',
  visaCategory: 'Business Visa',
  authority: 'Embassy of the Republic of Latvia in New Delhi / Office of Citizenship and Migration Affairs (PMLP)',
  channels: ['VFS Global Visa Application Centre', 'Embassy of the Republic of Latvia in New Delhi'],
  processingTime: {
    eVisa: 'N/A',
    standardSticker: '15 working days',
    expressSticker: 'N/A'
  },
  fees: {
    eVisaTotal: 'N/A',
    stickerConsularStandard: '90 EUR',
    vfsServiceFee: '1980 INR'
  },
  eVisa: {
    available: false,
    portal: 'N/A',
    territorialScope: 'N/A',
    validity: 'N/A',
    maxStay: 'N/A',
    invitationRequired: false,
    processing: 'N/A'
  },
  stayDuration: {
    eVisa: 'N/A',
    stickerSingleDouble: 'Up to 90 days within a 180-day period',
    stickerMultiple: 'Up to 90 days within a 180-day period'
  },
  entryType: 'Single / Multiple Entry',
  documents: [
    {
      key: 'passport',
      title: 'Valid Indian Passport',
      description: 'Original passport issued within the last 10 years, valid for at least 3 months beyond the intended departure date from the Schengen area, with at least 2 blank pages.',
      icon: 'passport',
      mandatory: true
    },
    {
      key: 'photographs',
      title: 'Passport Photographs (35x45mm)',
      description: 'Two recent (within 6 months) color photographs, 35x45mm, white background, neutral facial expression, with 70-80% face coverage.',
      icon: 'photo',
      mandatory: true
    },
    {
      key: 'visa_form',
      title: 'Schengen Visa Application Form',
      description: 'Completed and signed online visa application form generated from the official Latvian E-Visa portal (epvisa.mfa.gov.lv).',
      icon: 'form',
      mandatory: true
    },
    {
      key: 'ocma_invitation',
      title: 'OCMA Approved Official Invitation',
      description: 'Invitation approved by the Office of Citizenship and Migration Affairs (PMLP/OCMA) in Latvia, generated by the host organization.',
      icon: 'form',
      mandatory: true
    },
    {
      key: 'cover_letter',
      title: 'Employer Cover Letter',
      description: 'Original letter on Indian company letterhead introducing the applicant, explaining the commercial purpose, itinerary, and financial sponsorship.',
      icon: 'form',
      mandatory: true
    },
    {
      key: 'flight_booking',
      title: 'Flight Itinerary / Reservation',
      description: 'Round-trip flight reservation showing travel dates and flight numbers entering and leaving the Schengen area.',
      icon: 'flight',
      mandatory: true
    },
    {
      key: 'accommodation',
      title: 'Proof of Accommodation',
      description: 'Hotel bookings, accommodation voucher, or proof of lodging provided by the host organization in Latvia.',
      icon: 'hotel',
      mandatory: true
    },
    {
      key: 'travel_insurance',
      title: 'Travel Medical Insurance',
      description: 'Medical insurance policy covering all Schengen states with minimum coverage of 30,000 EUR for medical emergencies and repatriation.',
      icon: 'insurance',
      mandatory: true
    },
    {
      key: 'financial_proof',
      title: 'Proof of Financial Means',
      description: 'Bank statements for the last 3-6 months, stamped by the bank, along with Income Tax Returns (ITR) for the past 3 years.',
      icon: 'bank',
      mandatory: true
    }
  ]
};